server:
  port: 80 # 端口号

spring:
  freemarker:   # freemarker配置
    suffix: .ftl
    check-template-location: true # 是否缓存
    defaultEncoding: UTF-8
    templateLoaderPath: classpath:/demo # ftl所在路径
    content-type: text/html
    request-context-attribute: request
  mvc:
    static-path-pattern: /static/**  # 静态文件所在路径